
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package elyrasir.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import elyrasir.item.VingtpcItem;
import elyrasir.item.UnpcItem;
import elyrasir.item.HarponTactique4Item;
import elyrasir.item.HarponTactique3Item;
import elyrasir.item.HarponTactique2Item;
import elyrasir.item.HarponTactique1Item;
import elyrasir.item.HarponTactique0Item;
import elyrasir.item.HarponPol4Item;
import elyrasir.item.HarponPol3Item;
import elyrasir.item.HarponPol2Item;
import elyrasir.item.HarponPol1Item;
import elyrasir.item.HarponPol0Item;
import elyrasir.item.DixpcItem;
import elyrasir.item.DeuxcentpcItem;
import elyrasir.item.CinquantepcItem;
import elyrasir.item.CinqpcItem;
import elyrasir.item.CinqcentpcItem;
import elyrasir.item.CentpcItem;

import elyrasir.ElyrasirMod;

public class ElyrasirModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ElyrasirMod.MODID);
	public static final RegistryObject<Item> WHITECONCRETEBRICKS = block(ElyrasirModBlocks.WHITECONCRETEBRICKS);
	public static final RegistryObject<Item> WHITECONCRETEBIGSQUARE = block(ElyrasirModBlocks.WHITECONCRETEBIGSQUARE);
	public static final RegistryObject<Item> WHITECHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.WHITECHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> WHITECHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.WHITECHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> WHITECONCRETEPILLAR = block(ElyrasirModBlocks.WHITECONCRETEPILLAR);
	public static final RegistryObject<Item> WHITECONCRETETILES = block(ElyrasirModBlocks.WHITECONCRETETILES);
	public static final RegistryObject<Item> ORANGECONCRETEBRICKS = block(ElyrasirModBlocks.ORANGECONCRETEBRICKS);
	public static final RegistryObject<Item> ORANGECONCRETEBIGSQUARE = block(ElyrasirModBlocks.ORANGECONCRETEBIGSQUARE);
	public static final RegistryObject<Item> ORANGECHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.ORANGECHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> ORANGECHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.ORANGECHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> ORANGECONCRETEPILLAR = block(ElyrasirModBlocks.ORANGECONCRETEPILLAR);
	public static final RegistryObject<Item> ORANGECONCRETETILES = block(ElyrasirModBlocks.ORANGECONCRETETILES);
	public static final RegistryObject<Item> MAGENTACONCRETEBRICKS = block(ElyrasirModBlocks.MAGENTACONCRETEBRICKS);
	public static final RegistryObject<Item> MAGENTACONCRETEBIGSQUARE = block(ElyrasirModBlocks.MAGENTACONCRETEBIGSQUARE);
	public static final RegistryObject<Item> MAGENTACHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.MAGENTACHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> MAGENTACHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.MAGENTACHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> MAGENTACONCRETEPILLAR = block(ElyrasirModBlocks.MAGENTACONCRETEPILLAR);
	public static final RegistryObject<Item> MAGENTACONCRETETILES = block(ElyrasirModBlocks.MAGENTACONCRETETILES);
	public static final RegistryObject<Item> LIGHTBLUECONCRETEBRICKS = block(ElyrasirModBlocks.LIGHTBLUECONCRETEBRICKS);
	public static final RegistryObject<Item> LIGHTBLUECONCRETEBIGSQUARE = block(ElyrasirModBlocks.LIGHTBLUECONCRETEBIGSQUARE);
	public static final RegistryObject<Item> LIGHTBLUECHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.LIGHTBLUECHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> LIGHTBLUECHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.LIGHTBLUECHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> LIGHTBLUECONCRETEPILLAR = block(ElyrasirModBlocks.LIGHTBLUECONCRETEPILLAR);
	public static final RegistryObject<Item> LIGHTBLUECONCRETETILES = block(ElyrasirModBlocks.LIGHTBLUECONCRETETILES);
	public static final RegistryObject<Item> YELLOWCONCRETEBRICKS = block(ElyrasirModBlocks.YELLOWCONCRETEBRICKS);
	public static final RegistryObject<Item> YELLOWCONCRETEBIGSQUARE = block(ElyrasirModBlocks.YELLOWCONCRETEBIGSQUARE);
	public static final RegistryObject<Item> YELLOWCHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.YELLOWCHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> YELLOWCHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.YELLOWCHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> YELLOWCONCRETEPILLAR = block(ElyrasirModBlocks.YELLOWCONCRETEPILLAR);
	public static final RegistryObject<Item> YELLOWCONCRETETILES = block(ElyrasirModBlocks.YELLOWCONCRETETILES);
	public static final RegistryObject<Item> LIMECONCRETEBRICKS = block(ElyrasirModBlocks.LIMECONCRETEBRICKS);
	public static final RegistryObject<Item> LIMECONCRETEBIGSQUARE = block(ElyrasirModBlocks.LIMECONCRETEBIGSQUARE);
	public static final RegistryObject<Item> LIMECHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.LIMECHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> LIMECHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.LIMECHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> LIMECONCRETEPILLAR = block(ElyrasirModBlocks.LIMECONCRETEPILLAR);
	public static final RegistryObject<Item> LIMECONCRETETILES = block(ElyrasirModBlocks.LIMECONCRETETILES);
	public static final RegistryObject<Item> PINKCONCRETEBRICKS = block(ElyrasirModBlocks.PINKCONCRETEBRICKS);
	public static final RegistryObject<Item> PINKCONCRETEBIGSQUARE = block(ElyrasirModBlocks.PINKCONCRETEBIGSQUARE);
	public static final RegistryObject<Item> PINKCHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.PINKCHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> PINKCHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.PINKCHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> PINKCONCRETEPILLAR = block(ElyrasirModBlocks.PINKCONCRETEPILLAR);
	public static final RegistryObject<Item> PINKCONCRETETILES = block(ElyrasirModBlocks.PINKCONCRETETILES);
	public static final RegistryObject<Item> GRAYCONCRETEBRICKS = block(ElyrasirModBlocks.GRAYCONCRETEBRICKS);
	public static final RegistryObject<Item> GRAYCONCRETEBIGSQUARE = block(ElyrasirModBlocks.GRAYCONCRETEBIGSQUARE);
	public static final RegistryObject<Item> GRAYCHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.GRAYCHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> GRAYCHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.GRAYCHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> GRAYCONCRETEPILLAR = block(ElyrasirModBlocks.GRAYCONCRETEPILLAR);
	public static final RegistryObject<Item> GRAYCONCRETETILES = block(ElyrasirModBlocks.GRAYCONCRETETILES);
	public static final RegistryObject<Item> LIGHTGRAYCONCRETEBRICKS = block(ElyrasirModBlocks.LIGHTGRAYCONCRETEBRICKS);
	public static final RegistryObject<Item> LIGHTGRAYCONCRETEBIGSQUARE = block(ElyrasirModBlocks.LIGHTGRAYCONCRETEBIGSQUARE);
	public static final RegistryObject<Item> LIGHTGRAYCHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.LIGHTGRAYCHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> LIGHTGRAYCHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.LIGHTGRAYCHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> LIGHTGRAYCONCRETEPILLAR = block(ElyrasirModBlocks.LIGHTGRAYCONCRETEPILLAR);
	public static final RegistryObject<Item> LIGHTGRAYCONCRETETILES = block(ElyrasirModBlocks.LIGHTGRAYCONCRETETILES);
	public static final RegistryObject<Item> CYANCONCRETEBRICKS = block(ElyrasirModBlocks.CYANCONCRETEBRICKS);
	public static final RegistryObject<Item> CYANCONCRETEBIGSQUARE = block(ElyrasirModBlocks.CYANCONCRETEBIGSQUARE);
	public static final RegistryObject<Item> CYANCHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.CYANCHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> CYANCHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.CYANCHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> CYANCONCRETEPILLAR = block(ElyrasirModBlocks.CYANCONCRETEPILLAR);
	public static final RegistryObject<Item> CYANCONCRETETILES = block(ElyrasirModBlocks.CYANCONCRETETILES);
	public static final RegistryObject<Item> PURPLECONCRETEBRICKS = block(ElyrasirModBlocks.PURPLECONCRETEBRICKS);
	public static final RegistryObject<Item> PURPLECONCRETEBIGSQUARE = block(ElyrasirModBlocks.PURPLECONCRETEBIGSQUARE);
	public static final RegistryObject<Item> PURPLECHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.PURPLECHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> PURPLECHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.PURPLECHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> PURPLECONCRETEPILLAR = block(ElyrasirModBlocks.PURPLECONCRETEPILLAR);
	public static final RegistryObject<Item> PURLPLECONCRETETILES = block(ElyrasirModBlocks.PURLPLECONCRETETILES);
	public static final RegistryObject<Item> BLUECONCRETEBRICKS = block(ElyrasirModBlocks.BLUECONCRETEBRICKS);
	public static final RegistryObject<Item> BLUECONCRETEBIGSQUARE = block(ElyrasirModBlocks.BLUECONCRETEBIGSQUARE);
	public static final RegistryObject<Item> BLUECHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.BLUECHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> BLUECHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.BLUECHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> BLUECONCRETEPILLAR = block(ElyrasirModBlocks.BLUECONCRETEPILLAR);
	public static final RegistryObject<Item> BLUECONCRETETILES = block(ElyrasirModBlocks.BLUECONCRETETILES);
	public static final RegistryObject<Item> BROWNCONCRETEBRICKS = block(ElyrasirModBlocks.BROWNCONCRETEBRICKS);
	public static final RegistryObject<Item> BROWNCONCRETEBIGSQUARE = block(ElyrasirModBlocks.BROWNCONCRETEBIGSQUARE);
	public static final RegistryObject<Item> BROWNCHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.BROWNCHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> BROWNCHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.BROWNCHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> BROWNCONCRETEPILLAR = block(ElyrasirModBlocks.BROWNCONCRETEPILLAR);
	public static final RegistryObject<Item> BROWNCONCRETETILES = block(ElyrasirModBlocks.BROWNCONCRETETILES);
	public static final RegistryObject<Item> GREENCONCRETEBRICKS = block(ElyrasirModBlocks.GREENCONCRETEBRICKS);
	public static final RegistryObject<Item> GREENCONCRETEBIGSQUARE = block(ElyrasirModBlocks.GREENCONCRETEBIGSQUARE);
	public static final RegistryObject<Item> GREENCHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.GREENCHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> GREENCHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.GREENCHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> GREENCONCRETEPILLAR = block(ElyrasirModBlocks.GREENCONCRETEPILLAR);
	public static final RegistryObject<Item> GREENCONCRETETILES = block(ElyrasirModBlocks.GREENCONCRETETILES);
	public static final RegistryObject<Item> REDCONCRETEBRICKS = block(ElyrasirModBlocks.REDCONCRETEBRICKS);
	public static final RegistryObject<Item> REDCONCRETEBIGSQUARE = block(ElyrasirModBlocks.REDCONCRETEBIGSQUARE);
	public static final RegistryObject<Item> REDCHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.REDCHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> REDCHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.REDCHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> REDCONCRETEPILLAR = block(ElyrasirModBlocks.REDCONCRETEPILLAR);
	public static final RegistryObject<Item> REDCONCRETETILES = block(ElyrasirModBlocks.REDCONCRETETILES);
	public static final RegistryObject<Item> BLACKCONCRETEBRICKS = block(ElyrasirModBlocks.BLACKCONCRETEBRICKS);
	public static final RegistryObject<Item> BLACKCONCRETEBIGSQUARE = block(ElyrasirModBlocks.BLACKCONCRETEBIGSQUARE);
	public static final RegistryObject<Item> BLACKCHISLEDCREEPERCONCRETE = block(ElyrasirModBlocks.BLACKCHISLEDCREEPERCONCRETE);
	public static final RegistryObject<Item> BLACKCHISLEDSKELETONCONCRETE = block(ElyrasirModBlocks.BLACKCHISLEDSKELETONCONCRETE);
	public static final RegistryObject<Item> BLACKCONCRETEPILLAR = block(ElyrasirModBlocks.BLACKCONCRETEPILLAR);
	public static final RegistryObject<Item> BLACKCONCRETETILES = block(ElyrasirModBlocks.BLACKCONCRETETILES);
	public static final RegistryObject<Item> BLACKCONCRETEBRICKSLAB = block(ElyrasirModBlocks.BLACKCONCRETEBRICKSLAB);
	public static final RegistryObject<Item> BLUECONCRETEBRICKSLAB = block(ElyrasirModBlocks.BLUECONCRETEBRICKSLAB);
	public static final RegistryObject<Item> BROWNCONCRETEBRICKSLAB = block(ElyrasirModBlocks.BROWNCONCRETEBRICKSLAB);
	public static final RegistryObject<Item> CYANCONCRETEBRICKSLAB = block(ElyrasirModBlocks.CYANCONCRETEBRICKSLAB);
	public static final RegistryObject<Item> GRAYCONCRETEBRICKSLAB = block(ElyrasirModBlocks.GRAYCONCRETEBRICKSLAB);
	public static final RegistryObject<Item> GREENCONCRETEBRICKSLAB = block(ElyrasirModBlocks.GREENCONCRETEBRICKSLAB);
	public static final RegistryObject<Item> LIGHTBLUECONCRETEBRICKSLAB = block(ElyrasirModBlocks.LIGHTBLUECONCRETEBRICKSLAB);
	public static final RegistryObject<Item> LIGHTGRAYCONCRETEBRICKSLAB = block(ElyrasirModBlocks.LIGHTGRAYCONCRETEBRICKSLAB);
	public static final RegistryObject<Item> LIMECONCRETEBRICKSLAB = block(ElyrasirModBlocks.LIMECONCRETEBRICKSLAB);
	public static final RegistryObject<Item> MAGENTACONCRETEBRICKSLAB = block(ElyrasirModBlocks.MAGENTACONCRETEBRICKSLAB);
	public static final RegistryObject<Item> ORANGECONCRETEBRICKSLAB = block(ElyrasirModBlocks.ORANGECONCRETEBRICKSLAB);
	public static final RegistryObject<Item> PINKCONCRETEBRICKSLAB = block(ElyrasirModBlocks.PINKCONCRETEBRICKSLAB);
	public static final RegistryObject<Item> PURPLECONCRETEBRICKSLAB = block(ElyrasirModBlocks.PURPLECONCRETEBRICKSLAB);
	public static final RegistryObject<Item> REDCONCRETEBRICKSLAB = block(ElyrasirModBlocks.REDCONCRETEBRICKSLAB);
	public static final RegistryObject<Item> WHITECONCRETEBRICKSLAB = block(ElyrasirModBlocks.WHITECONCRETEBRICKSLAB);
	public static final RegistryObject<Item> YELLOWCONCRETEBRICKSLAB = block(ElyrasirModBlocks.YELLOWCONCRETEBRICKSLAB);
	public static final RegistryObject<Item> BLACKCONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.BLACKCONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> BLUECONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.BLUECONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> BROWNCONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.BROWNCONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> CYANCONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.CYANCONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> GRAYCONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.GRAYCONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> GREENCONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.GREENCONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> LIGHTBLUECONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.LIGHTBLUECONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> LIGHTGRAYCONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.LIGHTGRAYCONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> LIMECONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.LIMECONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> MAGENTACONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.MAGENTACONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> ORANGECONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.ORANGECONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> PINKCONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.PINKCONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> PURPLECONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.PURPLECONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> REDCONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.REDCONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> WHITECONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.WHITECONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> YELLOWCONCRETEBRICKSTAIRS = block(ElyrasirModBlocks.YELLOWCONCRETEBRICKSTAIRS);
	public static final RegistryObject<Item> BLACKCONCRETETILESSLAB = block(ElyrasirModBlocks.BLACKCONCRETETILESSLAB);
	public static final RegistryObject<Item> BLUECONCRETETILESSLAB = block(ElyrasirModBlocks.BLUECONCRETETILESSLAB);
	public static final RegistryObject<Item> BROWNCONCRETETILESSLAB = block(ElyrasirModBlocks.BROWNCONCRETETILESSLAB);
	public static final RegistryObject<Item> CYANCONCRETETILESSLAB = block(ElyrasirModBlocks.CYANCONCRETETILESSLAB);
	public static final RegistryObject<Item> GRAYCONCRETETILESSLAB = block(ElyrasirModBlocks.GRAYCONCRETETILESSLAB);
	public static final RegistryObject<Item> GREENCONCRETETILESSLAB = block(ElyrasirModBlocks.GREENCONCRETETILESSLAB);
	public static final RegistryObject<Item> LIGHTBLUECONCRETETILESSLAB = block(ElyrasirModBlocks.LIGHTBLUECONCRETETILESSLAB);
	public static final RegistryObject<Item> LIGHTGRAYCONCRETETILESSLAB = block(ElyrasirModBlocks.LIGHTGRAYCONCRETETILESSLAB);
	public static final RegistryObject<Item> LIMECONCRETETILESSLAB = block(ElyrasirModBlocks.LIMECONCRETETILESSLAB);
	public static final RegistryObject<Item> MAGENTACONCRETETILESSLAB = block(ElyrasirModBlocks.MAGENTACONCRETETILESSLAB);
	public static final RegistryObject<Item> ORANGECONCRETETILESSLAB = block(ElyrasirModBlocks.ORANGECONCRETETILESSLAB);
	public static final RegistryObject<Item> PINKCONCRETETILESSLAB = block(ElyrasirModBlocks.PINKCONCRETETILESSLAB);
	public static final RegistryObject<Item> PURPLECONCRETETILESSLAB = block(ElyrasirModBlocks.PURPLECONCRETETILESSLAB);
	public static final RegistryObject<Item> REDCONCRETETILESSLAB = block(ElyrasirModBlocks.REDCONCRETETILESSLAB);
	public static final RegistryObject<Item> WHITECONCRETETILESSLAB = block(ElyrasirModBlocks.WHITECONCRETETILESSLAB);
	public static final RegistryObject<Item> YELLOWCONCRETETILESSLAB = block(ElyrasirModBlocks.YELLOWCONCRETETILESSLAB);
	public static final RegistryObject<Item> HARPON_TACTIQUE_0 = REGISTRY.register("harpon_tactique_0", () -> new HarponTactique0Item());
	public static final RegistryObject<Item> HARPON_TACTIQUE_1 = REGISTRY.register("harpon_tactique_1", () -> new HarponTactique1Item());
	public static final RegistryObject<Item> HARPON_TACTIQUE_2 = REGISTRY.register("harpon_tactique_2", () -> new HarponTactique2Item());
	public static final RegistryObject<Item> HARPON_TACTIQUE_3 = REGISTRY.register("harpon_tactique_3", () -> new HarponTactique3Item());
	public static final RegistryObject<Item> HARPON_TACTIQUE_4 = REGISTRY.register("harpon_tactique_4", () -> new HarponTactique4Item());
	public static final RegistryObject<Item> HARPON_POL_0 = REGISTRY.register("harpon_pol_0", () -> new HarponPol0Item());
	public static final RegistryObject<Item> HARPON_POL_1 = REGISTRY.register("harpon_pol_1", () -> new HarponPol1Item());
	public static final RegistryObject<Item> HARPON_POL_2 = REGISTRY.register("harpon_pol_2", () -> new HarponPol2Item());
	public static final RegistryObject<Item> HARPON_POL_3 = REGISTRY.register("harpon_pol_3", () -> new HarponPol3Item());
	public static final RegistryObject<Item> HARPON_POL_4 = REGISTRY.register("harpon_pol_4", () -> new HarponPol4Item());
	public static final RegistryObject<Item> UNPC = REGISTRY.register("unpc", () -> new UnpcItem());
	public static final RegistryObject<Item> DIXPC = REGISTRY.register("dixpc", () -> new DixpcItem());
	public static final RegistryObject<Item> CINQPC = REGISTRY.register("cinqpc", () -> new CinqpcItem());
	public static final RegistryObject<Item> VINGTPC = REGISTRY.register("vingtpc", () -> new VingtpcItem());
	public static final RegistryObject<Item> CENTPC = REGISTRY.register("centpc", () -> new CentpcItem());
	public static final RegistryObject<Item> CINQUANTEPC = REGISTRY.register("cinquantepc", () -> new CinquantepcItem());
	public static final RegistryObject<Item> DEUXCENTPC = REGISTRY.register("deuxcentpc", () -> new DeuxcentpcItem());
	public static final RegistryObject<Item> CINQCENTPC = REGISTRY.register("cinqcentpc", () -> new CinqcentpcItem());
	public static final RegistryObject<Item> ATM = block(ElyrasirModBlocks.ATM);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
