package elyrasir.procedures;

import net.minecraftforge.fml.loading.FMLPaths;

import java.io.IOException;
import java.io.FileWriter;
import java.io.File;

import com.google.gson.GsonBuilder;
import com.google.gson.Gson;

public class LandCreateFileProcedure {
	public static void execute() {
		File file = new File("");
		com.google.gson.JsonObject Contree = new com.google.gson.JsonObject();
		com.google.gson.JsonObject Capitale = new com.google.gson.JsonObject();
		com.google.gson.JsonObject Cites = new com.google.gson.JsonObject();
		com.google.gson.JsonObject Arrondis = new com.google.gson.JsonObject();
		com.google.gson.JsonObject Cite1 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject arrond = new com.google.gson.JsonObject();
		com.google.gson.JsonObject arrond1 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject arrond2 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject arrond3 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject arrond4 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject arrond5 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject arrond6 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject arrond7 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject arrond8 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord0 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord1 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord2 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord3 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord4 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord5 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord6 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord7 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord8 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord9 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord10 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord11 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord12 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord13 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord14 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord15 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord16 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord17 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord18 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord19 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord20 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord21 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord22 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord23 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord24 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord25 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord26 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord27 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord28 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord29 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord30 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord31 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord32 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord33 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord34 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord35 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord36 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord37 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord38 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord39 = new com.google.gson.JsonObject();
		com.google.gson.JsonObject coord40 = new com.google.gson.JsonObject();
		file = new File((FMLPaths.GAMEDIR.get().toString() + "/config/pomme24/terrains"), File.separator + ("land" + ".json"));
		if (!file.exists()) {
			try {
				file.getParentFile().mkdirs();
				file.createNewFile();
			} catch (IOException exception) {
				exception.printStackTrace();
			}
			Contree.addProperty("Nom", "PommeV42");
			Capitale.addProperty("Nom", "Pommaria");
			Cites.addProperty("Nbcit\u00E9", 1);
			Arrondis.addProperty("Nbarrondissements", 9);
			arrond.addProperty("Nom", "Downtown");
			arrond1.addProperty("Nom", "Ile binaire");
			arrond2.addProperty("Nom", "none");
			arrond3.addProperty("Nom", "none");
			arrond4.addProperty("Nom", "none");
			arrond5.addProperty("Nom", "none");
			arrond6.addProperty("Nom", "none");
			arrond7.addProperty("Nom", "none");
			arrond8.addProperty("Nom", "none");
			Cite1.addProperty("Nom", "Pinath");
			coord0.addProperty("X", 0);
			coord0.addProperty("Y", 0);
			coord0.addProperty("Z", 0);
			coord1.addProperty("X", 0);
			coord1.addProperty("Y", 0);
			coord1.addProperty("Z", 0);
			coord2.addProperty("X", 0);
			coord2.addProperty("Y", 0);
			coord2.addProperty("Z", 0);
			coord3.addProperty("X", 0);
			coord3.addProperty("Y", 0);
			coord3.addProperty("Z", 0);
			coord4.addProperty("X", 0);
			coord4.addProperty("Y", 0);
			coord4.addProperty("Z", 0);
			coord5.addProperty("X", 0);
			coord5.addProperty("Y", 0);
			coord5.addProperty("Z", 0);
			coord6.addProperty("X", 0);
			coord6.addProperty("Y", 0);
			coord6.addProperty("Z", 0);
			coord7.addProperty("X", 0);
			coord7.addProperty("Y", 0);
			coord7.addProperty("Z", 0);
			coord8.addProperty("X", 0);
			coord8.addProperty("Y", 0);
			coord8.addProperty("Z", 0);
			coord9.addProperty("X", 0);
			coord9.addProperty("Y", 0);
			coord9.addProperty("Z", 0);
			coord10.addProperty("X", 0);
			coord10.addProperty("Y", 0);
			coord10.addProperty("Z", 0);
			coord11.addProperty("X", 0);
			coord11.addProperty("Y", 0);
			coord11.addProperty("Z", 0);
			coord12.addProperty("X", 0);
			coord12.addProperty("Y", 0);
			coord12.addProperty("Z", 0);
			coord13.addProperty("X", 0);
			coord13.addProperty("Y", 0);
			coord13.addProperty("Z", 0);
			coord14.addProperty("X", 0);
			coord14.addProperty("Y", 0);
			coord14.addProperty("Z", 0);
			coord15.addProperty("X", 0);
			coord15.addProperty("Y", 0);
			coord15.addProperty("Z", 0);
			coord16.addProperty("X", 0);
			coord16.addProperty("Y", 0);
			coord16.addProperty("Z", 0);
			coord17.addProperty("X", 0);
			coord17.addProperty("Y", 0);
			coord17.addProperty("Z", 0);
			coord18.addProperty("X", 0);
			coord18.addProperty("Y", 0);
			coord18.addProperty("Z", 0);
			coord19.addProperty("X", 0);
			coord19.addProperty("Y", 0);
			coord19.addProperty("Z", 0);
			coord20.addProperty("X", 0);
			coord20.addProperty("Y", 0);
			coord20.addProperty("Z", 0);
			coord21.addProperty("X", 0);
			coord21.addProperty("Y", 0);
			coord21.addProperty("Z", 0);
			coord22.addProperty("X", 0);
			coord22.addProperty("Y", 0);
			coord22.addProperty("Z", 0);
			coord23.addProperty("X", 0);
			coord23.addProperty("Y", 0);
			coord23.addProperty("Z", 0);
			coord24.addProperty("X", 0);
			coord24.addProperty("Y", 0);
			coord24.addProperty("Z", 0);
			coord25.addProperty("X", 0);
			coord25.addProperty("Y", 0);
			coord25.addProperty("Z", 0);
			coord26.addProperty("X", 0);
			coord26.addProperty("Y", 0);
			coord26.addProperty("Z", 0);
			coord27.addProperty("X", 0);
			coord27.addProperty("Y", 0);
			coord27.addProperty("Z", 0);
			coord28.addProperty("X", 0);
			coord28.addProperty("Y", 0);
			coord28.addProperty("Z", 0);
			coord29.addProperty("X", 0);
			coord29.addProperty("Y", 0);
			coord29.addProperty("Z", 0);
			coord30.addProperty("X", 0);
			coord30.addProperty("Y", 0);
			coord30.addProperty("Z", 0);
			coord31.addProperty("X", 0);
			coord31.addProperty("Y", 0);
			coord31.addProperty("Z", 0);
			coord32.addProperty("X", 0);
			coord32.addProperty("Y", 0);
			coord32.addProperty("Z", 0);
			coord33.addProperty("X", 0);
			coord33.addProperty("Y", 0);
			coord33.addProperty("Z", 0);
			coord34.addProperty("X", 0);
			coord34.addProperty("Y", 0);
			coord34.addProperty("Z", 0);
			coord35.addProperty("X", 0);
			coord35.addProperty("Y", 0);
			coord35.addProperty("Z", 0);
			coord36.addProperty("X", 0);
			coord36.addProperty("Y", 0);
			coord36.addProperty("Z", 0);
			coord37.addProperty("X", 0);
			coord37.addProperty("Y", 0);
			coord37.addProperty("Z", 0);
			coord38.addProperty("X", 0);
			coord38.addProperty("Y", 0);
			coord38.addProperty("Z", 0);
			coord39.addProperty("X", 0);
			coord39.addProperty("Y", 0);
			coord39.addProperty("Z", 0);
			coord.add("Coords40", coord39);
			coord.add("Coords39", coord38);
			coord.add("Coords38", coord37);
			coord.add("Coords37", coord36);
			coord.add("Coords36", coord35);
			coord.add("Coords35", coord34);
			coord.add("Coords34", coord33);
			coord.add("Coords33", coord32);
			coord.add("Coords32", coord31);
			coord.add("Coords31", coord30);
			coord.add("Coords30", coord29);
			coord.add("Coords29", coord28);
			coord.add("Coords28", coord27);
			coord.add("Coords27", coord26);
			coord.add("Coords26", coord25);
			coord.add("Coords25", coord24);
			coord.add("Coords24", coord23);
			coord.add("Coords23", coord22);
			coord.add("Coords22", coord21);
			coord.add("Coords21", coord20);
			coord.add("Coords20", coord19);
			coord.add("Coords19", coord18);
			coord.add("Coords18", coord17);
			coord.add("Coords17", coord16);
			coord.add("Coords16", coord15);
			coord.add("Coords15", coord14);
			coord.add("Coords14", coord13);
			coord.add("Coords13", coord12);
			coord.add("Coords12", coord11);
			coord.add("Coords11", coord10);
			coord.add("Coords10", coord9);
			coord.add("Coords9", coord8);
			coord.add("Coords8", coord7);
			coord.add("Coords7", coord6);
			coord.add("Coords6", coord5);
			coord.add("Coords5", coord4);
			coord.add("Coords4", coord3);
			coord.add("Coords3", coord2);
			coord.add("Coords2", coord1);
			coord.add("Coords1", coord0);
			Capitale.add("Coords", coord);
			Cite1.add("Coords", coord);
			arrond.add("Coords", coord);
			arrond1.add("Coords", coord);
			arrond2.add("Coords", coord);
			arrond3.add("Coords", coord);
			arrond4.add("Coords", coord);
			arrond5.add("Coords", coord);
			arrond6.add("Coords", coord);
			arrond7.add("Coords", coord);
			arrond8.add("Coords", coord);
			Arrondis.add("Arondissement1", arrond);
			Arrondis.add("Arondissement2", arrond1);
			Arrondis.add("Arondissement3", arrond2);
			Arrondis.add("Arondissement4", arrond3);
			Arrondis.add("Arondissement5", arrond4);
			Arrondis.add("Arondissement6", arrond5);
			Arrondis.add("Arondissement7", arrond6);
			Arrondis.add("Arondissement8", arrond7);
			Arrondis.add("Arondissement9", arrond8);
			Capitale.add("Arrondissements", Arrondis);
			Cites.add("Cite1", Cite1);
			Contree.add("Capitale", Capitale);
			Contree.add("Cit\u00E9s", Cites);
			{
				Gson mainGSONBuilderVariable = new GsonBuilder().setPrettyPrinting().create();
				try {
					FileWriter fileWriter = new FileWriter(file);
					fileWriter.write(mainGSONBuilderVariable.toJson(Contree));
					fileWriter.close();
				} catch (IOException exception) {
					exception.printStackTrace();
				}
			}
		}
	}
}
